### PR TITLE
[#2383] Change k8s lease expiration calculation

### LINKED ISSUE #2383: Calculation of lease timeout uses TimeOfDay (Lease can't be aquired the next day!)
**Version Information**
Akka.Management 1.5.15

**Describe the bug**
The lease timeout calculation is incorrect, because it is based on the current time of day.
I noticed this because we shut off our developer VMs every day. So every morning the leases just can't be aquired, because the last written time into the lease is from the evening.

**To Reproduce**
1. Start a node that acquires a kubernetes lease
2. shut down the node
3. Start it on the next day before the time you shut it down the day before
4. Lease can't be acquired
(Or simply modify the lease manually)

**Expected behavior**
The lease should be aquired instantly on the next day.

**Actual behavior**
The lease can't be aquired till the time when the node shut down the previous day.

**Environment**
Linux inside a kubernetes cluster

### PR DESCRIPTION
**Pull request by Arkatufus**
Fixes #2383

## Changes

Change Akka.Coordination.KubernetesApi lease timeout/expiration calculation from `DateTime.TimeOfDay.TotalMilliseconds` to `DateTime.Ticks`.

## Notes

The wire format is untouched, but the content and its context does. `LeaseSpec.Time` now represents the absolute `DateTime` ticks when a lease will expire, instead of the time offset (in milliseconds) when the lease will expire.

> [!WARNING]
>
> This is not backward compatible with any version below 1.5.18, a CVE will need to be issued to warn users about this breaking change.

## Checklist

For significant changes, please ensure that the following have been completed (delete if not relevant):

* [x] This change follows the [Akka.NET API Compatibility Guidelines](https://getakka.net/community/contributing/api-changes-compatibility.html).
* [x] This change follows the [Akka.NET Wire Compatibility Guidelines](https://getakka.net/community/contributing/wire-compatibility.html).
* [x] I have [reviewed my own pull request](https://getakka.net/community/contributing/index.html#review-your-own-pull-requests).

### CODE REVIEW

File: src/coordination/kubernetes/Akka.Coordination.KubernetesApi/KubernetesApi.cs [hunk 1]
```diff
@@ -41,7 +41,7 @@ public LeaseResource(string? owner, string version, long time)
 
         public string? Owner { get; }
         public string Version { get; }
-        public long Time { get; }
+        public DateTime Time { get; }
```
Comment (Arkatufus) [inline src/coordination/kubernetes/Akka.Coordination.KubernetesApi/KubernetesApi.cs:44]: The internal lease resource timeout property now stores the absolute expiration date and time, not the milliseconds offset until lease expiration

File: src/coordination/kubernetes/Akka.Coordination.KubernetesApi/LeaseActor.cs [hunk 2]
```diff
@@ -551,11 +556,8 @@ private void ExecuteLeaseLockCallback(Action<Exception?> callback, Exception? re
             return GoTo(Granting.Instance).Using(new OperationInProgress(reply, version, leaseLost));
         }
 
-        private bool HasLeaseTimedOut(long leaseTime)
-            => DateTime.UtcNow.TimeOfDay.TotalMilliseconds > 
-               leaseTime + 
-               _settings.TimeoutSettings.HeartbeatTimeout.TotalMilliseconds -
-               2 * _settings.TimeoutSettings.HeartbeatInterval.TotalMilliseconds;
+        private bool HasLeaseTimedOut(DateTime leaseTime)
+            => DateTime.UtcNow > leaseTime + _heartbeatTimeout - _heartbeatOffset;
```
Comment (Arkatufus) [inline src/coordination/kubernetes/Akka.Coordination.KubernetesApi/LeaseActor.cs:560]: Lease timeout calculation is now based on absolute date and time

File: src/coordination/kubernetes/Akka.Coordination.KubernetesApi/Internal/KubernetesApiImpl.cs [hunk 3]
```diff
@@ -384,7 +384,7 @@ private LeaseResource ToLeaseResource(object obj)
             return new LeaseResource(
                 string.IsNullOrWhiteSpace(lease.Spec.Owner) ? null : lease.Spec.Owner,
                 lease.Metadata.ResourceVersion,
-                lease.Spec.Time);
+                DateTime.SpecifyKind(new DateTime(lease.Spec.Time), DateTimeKind.Utc));
```
Comment (Arkatufus) [inline src/coordination/kubernetes/Akka.Coordination.KubernetesApi/Internal/KubernetesApiImpl.cs:387]: Converts the stored ticks to `DateTime` and set the `Kind` to UTC

File: src/coordination/kubernetes/Akka.Coordination.KubernetesApi/Models/LeaseCustomResource.cs [hunk 4]
```diff
@@ -39,7 +39,7 @@ public LeaseSpec()
         public LeaseSpec(string? owner, DateTime time)
         {
             Owner = owner;
-            Time = (long) time.TimeOfDay.TotalMilliseconds;
+            Time = time.Ticks;
```
Comment (Arkatufus) [inline src/coordination/kubernetes/Akka.Coordination.KubernetesApi/Models/LeaseCustomResource.cs:42]: Stores the timeout value to absolute date and time expiration value instead of the millisecond offset until expiration

**Review by Arkatufus — COMMENTED** [review]
Self review

**Review by Aaronontheweb — APPROVED** [review]
LGTM
